version: '3.8'

services:
  api:
    container_name: escalando_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=MyPassword123
      - DB_NAME=escalando_db
      - DATABASE_URL=postgresql://postgres:MyPassword123@db:5432/escalando_db
    restart: always

  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: MyPassword123
      POSTGRES_DB: escalando_db
      POSTGRES_USER: postgres
    container_name: escalando-db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  migrations:
    container_name: escalando_migrations
    build:
      context: .
      target: development
    command: npm run migration:run
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=MyPassword123
      - DB_NAME=escalando_db
      - DB_PORT=5432
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: escalando-adminer