
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddlgwcmkoufibfornlyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkbGd3Y21rb3VmaWJmb3JubHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTI3NDMsImV4cCI6MjA1ODQ4ODc0M30.swdlSLgOCw49VMF9c0a11Wr5sOss5FCXZ9Lm4oMGtnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Function to create a professional record by adding to pending_professionals table
export const inviteProfessional = async (email: string, name: string, specialty: string, role: string) => {
  try {
    // Insert the professional into the pending_professionals table
    const { data, error } = await supabase
      .from('pending_professionals')
      .insert({
        email,
        name,
        specialty,
        role,
        status: 'pending'
      });
    
    if (error) throw error;
    
    return { data, error: null };
  } catch (error) {
    console.error("Error inviting professional:", error);
    return { data: null, error };
  }
};
